set number
set relativenumber
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent
set expandtab
set cindent
set scrolloff=8
set sidescrolloff=8
set wildmenu
set completeopt=menu,menuone,noselect
